<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$env = getenv('APPLICATION_ENV') ?: 'production';
$appConfDir = getenv('APP_CONF_DIR') ?: null;

if ($env !== 'testing') {
    $confPaths = ['config/autoload/{,*.}{global,local}.php'];
}
$dataPath = 'data';
if (!empty($appConfDir)) {
    $confPaths[] = $appConfDir . '/local.php';
    $dataPath = $appConfDir . '/data';
    if (!is_dir($dataPath . '/cache')) {
        if (!mkdir($concurrentDirectory = $dataPath . '/cache') && !is_dir($concurrentDirectory)) {
            throw new \RuntimeException(sprintf('Directory "%s" was not created', $concurrentDirectory));
        }
    }
}

return [
    'modules' => [
        'Laminas\I18n',
        'Laminas\Mail',
        'Laminas\Log',
        'Monarc\Core',
        'Monarc\FrontOffice',
        'Laminas\Cache',
        'Laminas\Form',
        'Laminas\InputFilter',
        'Laminas\Filter',
        'Laminas\Paginator',
        'Laminas\Hydrator',
        'Laminas\Di',
        'Laminas\Router',
        'Laminas\Validator',
        'DoctrineModule',
        'DoctrineORMModule',
    ],
    'module_listener_options' => [
        'module_paths' => [
            './module',
            './vendor'
        ],
        'config_glob_paths' => $confPaths,
        'config_cache_enabled' => $env === 'production',
        'config_cache_key' => 'c8aaaaa11586f8b1bf5565cc6064e70a', // md5('config_cache_key_monarc')
        'module_map_cache_enabled' => $env === 'production',
        'module_map_cache_key' => '664579376c4dcdcaa0bcdd0f7e7bf25b', // md5('module_map_cache_key_monarc'),
        'cache_dir' => $dataPath . '/cache/',
        'check_dependencies' => $env !== 'production',
    ],
];
